class_name LevelConfig
extends RefCounted

## Data for the test level that character_switcher.gd builds in code (the level
## scene stays minimal because the editor keeps clobbering it). Move these into a
## real level scene's inspector when the dev harness is retired.
##
## This is a VERTICAL level: a tall zigzag tower you climb from the ground floor up.
## The camera follows the player (character_switcher._physics_process), so there is no
## height limit -- add more PLATFORMS rows to build higher. Steps are ~70-95px apart,
## staggered left/right, so each is one jump + an air-jump from the one below.

## Player start on the ground floor, left of the tower base so you spawn in the clear.
## Also the respawn point on death / falling out.
const SPAWN := Vector2(-450, 0)
## Fall below this (well under the ground floor) and you respawn instead of dropping
## forever. The floor sits at y~0, so falling off the tower drops you back to it, not
## to death -- you only respawn if you leave the world past the floor's edges.
const DEATH_Y := 300.0

## Jump-up platforms, each [center_x, top_y, width]. A rising zigzag tower: the player
## climbs ground -> P1 -> P2 -> ... using the jump + generous air jumps. One-way, so you
## jump up through each and land on top (press down+jump to drop back through).
## Add/remove rows to change the height; keep steps within ~100px of the row below.
const PLATFORMS := [
	[-330.0, -70.0, 180.0],
	[190.0, -138.0, 150.0],
	[-150.0, -215.0, 140.0],
	[300.0, -301.0, 160.0],
	[-260.0, -396.0, 150.0],
	[110.0, -464.0, 190.0],
	[-310.0, -541.0, 140.0],
	[260.0, -627.0, 160.0],
	[-120.0, -722.0, 150.0],
	[330.0, -790.0, 170.0],
	[-230.0, -867.0, 150.0],
	[150.0, -953.0, 140.0],
	[-320.0, -1048.0, 160.0],
	[220.0, -1116.0, 150.0],
	[-160.0, -1193.0, 180.0],
	[300.0, -1279.0, 140.0],
	[-250.0, -1374.0, 160.0],
	[120.0, -1442.0, 150.0],
	[-300.0, -1519.0, 170.0],
	[250.0, -1605.0, 150.0],
	[-180.0, -1700.0, 160.0],
	[90.0, -1768.0, 190.0],
	[-290.0, -1845.0, 150.0],
	[230.0, -1931.0, 160.0],
	[-140.0, -2026.0, 150.0],
	[300.0, -2094.0, 160.0],
	[-240.0, -2171.0, 150.0],
	[130.0, -2257.0, 180.0],
	[-300.0, -2352.0, 150.0],
	[210.0, -2420.0, 160.0],
	# Summit arena: an extra-long platform capping the tower, packed with the horde below.
	[0.0, -2520.0, 3600.0],
]

## Enemy spawn roster. Each entry: { id, name, pos, and any Enemy @export to override
## per-instance }. Spread up the tower, every few platforms, so the climb is contested
## without swarming any one ledge. Alternating Kebus (melee + straight bolt) and Baghel
## (ranged ground surge).
##
## STOP ENEMIES FROM "HOMING" YOU: it's the `ranged_mode` export. "aimed" (the default)
## points each shot at the player's torso the moment it fires -- that tracking is what
## reads as homing (the projectile itself never steers; homing=0 for enemies). "forward"
## fires straight ahead in the enemy's facing instead, so a shot only hits if you're in
## its line. Every entry here is "forward". (Separately, `aggro` = false, the default,
## keeps them guarding their platform rather than chasing you.)
const ROSTER := [
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-190.0, -215.0),
		"ranged_mode": "forward",  # fire straight ahead, not tracked at the player
		"muzzle_offset": Vector2(18, -22),  # bolt leaves at body height (the aimed default, -46, sits above his head)
		"ranged_hitbox_extents": Vector2(7, 10),  # cover the body so a same-level shot connects
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(70.0, -464.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	# A sleeper guarding this ledge -- dozes until you get close, then rages a ground AoE.
	{"scene": "res://scenes/nasen.tscn", "name": "Nasen", "pos": Vector2(-160.0, -722.0)},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(110.0, -953.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-200.0, -1193.0),
		"ranged_mode": "forward",  # fire straight ahead, not tracked at the player
		"muzzle_offset": Vector2(18, -22),  # bolt leaves at body height (the aimed default, -46, sits above his head)
		"ranged_hitbox_extents": Vector2(7, 10),  # cover the body so a same-level shot connects
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"scene": "res://scenes/nasen.tscn", "name": "Nasen", "pos": Vector2(80.0, -1442.0)},
	{"scene": "res://scenes/nasen.tscn", "name": "Nasen", "pos": Vector2(-220.0, -1700.0)},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(190.0, -1931.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-280.0, -2171.0),
		"ranged_mode": "forward",  # fire straight ahead, not tracked at the player
		"muzzle_offset": Vector2(18, -22),  # bolt leaves at body height (the aimed default, -46, sits above his head)
		"ranged_hitbox_extents": Vector2(7, 10),  # cover the body so a same-level shot connects
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(170.0, -2420.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	# --- Summit horde: 40 enemies packed across the extra-long top platform (y=-2520). All "forward" (no homing); patrol_distance trimmed so they hold their slot. ---
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-1700.0, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-1612.8, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-1525.6, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-1438.5, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-1351.3, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-1264.1, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-1176.9, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-1089.7, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-1002.6, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-915.4, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-828.2, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-741.0, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-653.8, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-566.7, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-479.5, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-392.3, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-305.1, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-217.9, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(-130.8, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(-43.6, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(43.6, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(130.8, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(217.9, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(305.1, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(392.3, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(479.5, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(566.7, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(653.8, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(741.0, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(828.2, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(915.4, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(1002.6, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(1089.7, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(1176.9, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(1264.1, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(1351.3, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(1438.5, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(1525.6, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
	{"id": "kebus", "name": "Kebus", "pos": Vector2(1612.8, -2520.0),
		"ranged_mode": "forward", "patrol_distance": 40.0,
		"muzzle_offset": Vector2(18, -22), "ranged_hitbox_extents": Vector2(7, 10),
		"ranged_particle": "res://vfx/enemy/kebus/attack/attack_bolt.tscn"},
	{"id": "baghel", "name": "Baghel", "pos": Vector2(1700.0, -2520.0),
		"ranged_mode": "forward", "ranged_range": 130.0, "ranged_travel": 100.0, "projectile_speed": 200.0,
		"patrol_distance": 40.0,
		"ranged_particle": "res://vfx/enemy/baghel/attack/attack_ground_wave.tscn",
		"ranged_hitbox_extents": Vector2(4, 15), "ranged_hitbox_offset": Vector2(0, -9),
		"muzzle_offset": Vector2(16, 1), "ranged_damage": 7.0,
		"idle_loop_from": 1, "idle_loop_to": 3, "idle_loop_time": 2.0,
		"idle_time_min": 5.0, "idle_time_max": 7.0},
]
