#!/usr/bin/env python3
"""Collapse the AI-generated sprite sheets onto a small hand-authored palette.

The sheets were generated at high resolution and downscaled to ~32px, so the
resampler smeared every region into hundreds of near-identical shades (the idle
sheet has 1595 unique colours across 1795 opaque pixels -- effectively one
colour per pixel) and wrapped everything in a dark antialiasing rind. Nearest-
colour matching alone does not fix that: the rind sits between two materials, so
it matches whichever ramp happens to be closer and the character keeps its
muddy black outline.

So this runs in three passes instead:

  1. classify -- put each pixel in a material (hair/skin/jacket/...) using hue
     bands, not distance. Hue survives the downscale far better than value does:
     the jacket stays at H~18 whether the pixel is lit or shadowed, while its
     value slides all over the place.
  2. shade     -- inside a material, map each pixel's luma through that
     material's FIXED cut points. The cuts are calibrated once, globally, and
     are the same for every sheet -- which is the whole point of the tool. An
     earlier version ranked pixels per sheet and split on quantiles; that forced
     every material into the same 35/40/25 light/mid/dark split no matter what
     it actually looked like, so his flat 91%-midtone hair came out banded and
     his dark trousers came out mottled like camo. Worse, per-sheet quantiles
     mean the same brown maps to different shades in idle and in run.
  3. de-ink    -- pixels too dark or too odd to classify are the resample rind.
     They get flood-voted from their settled neighbours. Where the rind traces
     the silhouette or runs between two materials it is a real outline and takes
     that material's dark RIM tint; elsewhere it is dirt and just copies its
     neighbour. Either way it inherits rather than being shaded in pass 2: a rind
     pixel's colour is a blend of two regions, so its own luma means nothing.

A final optional de-speckle flips lone pixels that disagree with all 8 of their
neighbours. At this scale the resampler leaves plenty of those, and one stray
teal pixel in a grey boot is far more visible than it would be at 4x the size.

Non-destructive: writes to a sibling output dir, never over the source.

    python3 tools/repalette.py ../mygame/art/characters/khalid/frames/khalid_idle_frames.png --debug
    python3 tools/repalette.py ../mygame/art/characters/khalid/frames/ -o /tmp/repal
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from PIL import Image

# --- palette -----------------------------------------------------------------
# HUE and SATURATION come from Khalid.png, the hand-drawn portrait -- the only
# art with authoritative colours. VALUE does not: the portrait is a 1080px
# illustration with big brightly-lit flats, and pasting its brightness onto a
# 32px sprite makes him read like a toy. Measured across all 17 sheets, the
# source sprites live in a dark compressed band (luma p5-p95 = 0.04-0.42) while
# a portrait-valued ramp spans 0.12-0.79. So each ramp is anchored to its
# material's own measured median luma in the sheets.
# Identity from the portrait, form from the sprite.
#
# Generated by `--calibrate`; regenerate after changing SHADES/IDENTITY/GAIN.
# Ordered light -> dark, with the last entry the RIM (outline only, never
# reachable by shading). CUTS are the luma thresholds *in source space* that
# select between them -- ascending, so len(CUTS) == SHADES - 1.
#
# Colours and cuts are deliberately separate: cuts say WHERE to change shade and
# come from the sheets' measured distribution, colours say WHAT to paint and are
# spread apart by GAIN so the steps are actually visible.
PALETTE: dict[str, tuple[str, ...]] = {
    "hair": ("#941E1E", "#811A1A", "#721717", "#651414", "#531111", "#330A0A"),  # median 0.196
    "skin": ("#0DA29B", "#0B8B84", "#086863", "#064946", "#021F1E", "#021312"),  # median 0.294
    "jacket": ("#52382B", "#4B3328", "#37261D", "#271B15", "#160F0C", "#0E0907"),  # median 0.165
    "trim": ("#EBE123", "#D1C81F", "#A7A019", "#797412", "#3B3809", "#242305"),  # median 0.575
    "pants": ("#34432F", "#2F3D2B", "#293525", "#1D251A", "#161C14", "#0E120C"),  # median 0.186
    "metal": ("#8E969E", "#60656A", "#43474B", "#2A2C2E", "#141516", "#0D0D0E"),  # median 0.276
}
CUTS: dict[str, tuple[float, ...]] = {
    "hair": (0.172, 0.189, 0.205, 0.223),
    "skin": (0.186, 0.262, 0.323, 0.377),
    "jacket": (0.112, 0.146, 0.190, 0.208),
    "trim": (0.332, 0.508, 0.630, 0.694),
    "pants": (0.136, 0.165, 0.196, 0.210),
    "metal": (0.150, 0.240, 0.308, 0.390),
}
SHADES = 5  # entries per ramp reachable by shading; the trailing one is rim

# Hue/saturation per material, read off the portrait. Metal and pants are not in
# the portrait (it is a bust) so they are taken from the sprites' own hue bands.
# `--calibrate` regenerates PALETTE from these plus the sheets' measured luma.
IDENTITY: dict[str, tuple[float, float]] = {
    "hair": (0.0, 0.80),
    "skin": (177.0, 0.92),
    "jacket": (20.0, 0.47),
    "trim": (57.0, 0.85),
    "pants": (105.0, 0.30),
    "metal": (210.0, 0.10),
}
# Painting the measured percentiles literally reproduces the sheets' flatness --
# the hair's whole p30-p92 span is 0.18-0.24, five shades of nothing. So each
# shade is pushed away from its material's median by GAIN, which keeps the
# overall tone anchored (that is what stops him reading like a toy) while giving
# the steps enough separation to see.
#
# The push is a power law on the RATIO to the median, not a multiple of the
# difference: skin and metal are spread widely enough that scaling the
# difference drives the darkest shade past black into negative luma, whereas a
# ratio raised to a power stays positive however wide the spread.
GAIN = 1.5
RIM_FACTOR = 0.62
# Floor on how far the push may darken a shade, as a fraction of the material's
# median. Skin's measured spread is wide enough that its darkest band lands near
# black, and a black shadow on teal skin reads as a hole punched in him rather
# than as shading.
SHADE_FLOOR = 0.30
# Sheets free of red VFX. The spear/death/spawn effects classify as `hair` and
# drag its calibration far too bright, so they are excluded from measurement.
CALIBRATION_SHEETS = ("idle", "run", "jump", "fall", "land", "slam", "dash", "special_default")


@dataclass(frozen=True)
class Rule:
    """Hue/sat/val window that claims a pixel for a material. First match wins."""

    material: str
    hue: tuple[float, float]  # degrees, inclusive-exclusive; wraps if lo > hi
    sat: tuple[float, float] = (0.0, 1.01)
    val: tuple[float, float] = (0.0, 1.01)


# Ordered most-specific first. Anything that matches nothing here is treated as
# rind and resolved from its neighbours, so this table only has to be confident,
# not exhaustive -- it is safer to leave a weird pixel unclaimed than to guess.
RULES: tuple[Rule, ...] = (
    Rule("trim", hue=(40, 75), sat=(0.30, 1.01), val=(0.28, 1.01)),
    # Real skin is vividly teal (S 0.66-0.95, portrait says 0.92). A low floor
    # here also swept up the dark blue-grey pixels in the boots and scattered
    # teal specks down his legs; the two populations are cleanly bimodal with a
    # gap at ~0.45, so anything below that is left for the neighbour vote.
    Rule("skin", hue=(150, 205), sat=(0.45, 1.01)),
    Rule("pants", hue=(75, 150), sat=(0.10, 1.01)),
    # Hair before jacket: both land in the reds, but the hair keeps the
    # portrait's S~0.8 while the jacket sits near S~0.5.
    Rule("hair", hue=(335, 12), sat=(0.45, 1.01)),
    Rule("jacket", hue=(8, 48), sat=(0.22, 1.01)),
    Rule("metal", hue=(0, 360), sat=(0.0, 0.22)),
)

# Rind is dark AND washed out. Requiring both matters: of the pixels under
# INK_VAL, 166 of 226 still carry saturation >= 0.2, i.e. they are a material in
# deep shadow -- the crease under an armpit, the fold inside a coat. Treating
# every dark pixel as rind threw that hue away and handed those creases to the
# neighbour vote, which filled them in flat. Now they keep their material and
# simply land in its darkest shade.
INK_VAL = 0.11
INK_SAT = 0.30
# ...but below DEAD_VAL the saturation test has to be abandoned, because
# saturation stops meaning anything there. A pixel like #070100 reports S=1.00
# purely because one channel is 7 and the others are ~0; it is black, not
# vivid red. Trusting that let outline pixels on his boots classify as hair and
# paint red dots on his feet.
DEAD_VAL = 0.05
ALPHA_CUT = 128  # pixel art wants hard edges; the AI's soft halo goes away
DESPECKLE_SUPPORT = 1  # min agreeing neighbours a pixel needs to survive
# Smoothing is off by default now. It existed to hide the mottle that per-sheet
# quantiles created; fixed cuts do not mottle, so it is no longer paying for
# itself -- and a 3x3 mean erases exactly the 1px creases (armpits, coat folds)
# that give the sprite its form, by averaging one dark pixel with eight lit ones.
SMOOTH_RADIUS = 0
# The gold collar/buckles are a 1px accent the downscale left as scattered lone
# pixels -- despeckling reads them as noise and wipes the collar off his neck.
DESPECKLE_EXEMPT = frozenset({"trim"})

# Flat colours for --debug masks, in PALETTE order + rind.
DEBUG_COLORS = {
    "hair": (255, 0, 0),
    "skin": (0, 255, 255),
    "jacket": (150, 90, 40),
    "trim": (255, 255, 0),
    "pants": (60, 220, 60),
    "metal": (200, 200, 200),
    None: (255, 0, 255),  # rind, before it gets voted away
}


def hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def rgb_to_hsv(rgb: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Vectorised RGB->HSV. rgb is float (..., 3) in 0..1; hue comes back in degrees."""
    mx = rgb.max(axis=-1)
    mn = rgb.min(axis=-1)
    span = mx - mn
    r, g, b = rgb[..., 0], rgb[..., 1], rgb[..., 2]

    hue = np.zeros_like(mx)
    safe = np.where(span == 0, 1.0, span)  # avoid 0/0; masked out below anyway
    hue = np.where(mx == r, ((g - b) / safe) % 6, hue)
    hue = np.where(mx == g, ((b - r) / safe) + 2, hue)
    hue = np.where(mx == b, ((r - g) / safe) + 4, hue)
    hue = np.where(span == 0, 0.0, hue * 60.0)

    sat = np.where(mx == 0, 0.0, span / np.where(mx == 0, 1.0, mx))
    return hue, sat, mx


def luma(rgb: np.ndarray) -> np.ndarray:
    """Rec.601 luma, on 0..1 float RGB. Used only to rank pixels within a material."""
    return rgb[..., 0] * 0.299 + rgb[..., 1] * 0.587 + rgb[..., 2] * 0.114


def classify(rgb: np.ndarray, opaque: np.ndarray) -> np.ndarray:
    """Label every opaque pixel with a material index, or -1 for rind.

    Returns an int8 array shaped like the image.
    """
    hue, sat, val = rgb_to_hsv(rgb)
    labels = np.full(rgb.shape[:2], -1, dtype=np.int8)
    names = list(PALETTE)

    # Rind first so no rule can claim a near-black pixel on a meaningless hue.
    ink = (val < DEAD_VAL) | ((val < INK_VAL) & (sat < INK_SAT))
    unclaimed = opaque & ~ink

    for rule in RULES:
        lo, hi = rule.hue
        in_hue = (hue >= lo) & (hue < hi) if lo <= hi else (hue >= lo) | (hue < hi)
        hit = (
            unclaimed
            & in_hue
            & (sat >= rule.sat[0])
            & (sat < rule.sat[1])
            & (val >= rule.val[0])
            & (val < rule.val[1])
        )
        labels[hit] = names.index(rule.material)
        unclaimed &= ~hit

    return labels


def swatch_table() -> tuple[np.ndarray, list[str]]:
    """Flatten PALETTE into a lookup table of RGB rows, plus each row's material."""
    rows, owners = [], []
    for name, ramp in PALETTE.items():
        for c in ramp:
            rows.append(hex_to_rgb(c))
            owners.append(name)
    return np.array(rows, dtype=np.uint8), owners


def _blur_within(values: np.ndarray, mask: np.ndarray, radius: int) -> np.ndarray:
    """Box-blur `values` using only pixels inside `mask`, so regions do not bleed."""
    total = np.zeros_like(values)
    count = np.zeros_like(values)
    masked = np.where(mask, values, 0.0)
    weight = mask.astype(np.float32)
    for dy in range(-radius, radius + 1):
        for dx in range(-radius, radius + 1):
            total += np.roll(np.roll(masked, dy, 0), dx, 1)
            count += np.roll(np.roll(weight, dy, 0), dx, 1)
    return np.where(count > 0, total / np.maximum(count, 1e-6), values)


def assign_shades(
    rgb: np.ndarray,
    labels: np.ndarray,
    opaque: np.ndarray,
    smooth: int,
) -> np.ndarray:
    """Map each classified pixel to a swatch through its material's fixed CUTS.

    The cuts are absolute luma thresholds, identical for every sheet, so a given
    source brown always becomes the same brown -- that consistency across sheets
    is the reason this tool exists. It also means a material keeps its real
    light/dark balance instead of being forced into fixed proportions, so flat
    areas stay flat and a crease that is genuinely darker than the cloth around
    it drops a step or two on its own.

    Returns swatch indices into swatch_table(), -1 where still unsettled (rind).
    """
    idx = np.full(labels.shape, -1, dtype=np.int16)
    lum = luma(rgb)
    offset = 0

    for m, name in enumerate(PALETTE):
        mask = opaque & (labels == m)
        if mask.any():
            field = _blur_within(lum, mask, smooth) if smooth else lum
            # CUTS ascend dark -> light; PALETTE is ordered light -> dark.
            rank = np.searchsorted(np.asarray(CUTS[name]), field[mask], side="left")
            idx[mask] = offset + (SHADES - 1 - np.clip(rank, 0, SHADES - 1))
        offset += len(PALETTE[name])

    return idx


def _neighbour_votes(idx: np.ndarray, n_swatches: int) -> np.ndarray:
    """votes[s] = how many of each pixel's 8 neighbours carry swatch s."""
    votes = np.zeros((n_swatches, *idx.shape), dtype=np.int16)
    for s in range(n_swatches):
        padded = np.pad((idx == s).astype(np.int16), 1)
        for dy in (0, 1, 2):
            for dx in (0, 1, 2):
                if dy == 1 and dx == 1:
                    continue
                votes[s] += padded[dy : dy + idx.shape[0], dx : dx + idx.shape[1]]
    return votes


def _is_outline(rind: np.ndarray, labels: np.ndarray, opaque: np.ndarray) -> np.ndarray:
    """Split the rind into real outline vs. interior resample noise.

    The AI's dark rind is doing two different jobs, and they need opposite
    treatment. Where it traces the silhouette or runs between two materials it
    is a genuine outline -- that is the edge that separates his arm from his
    torso, and deleting it is what flattened the sprite. Where it is a lone dark
    speck floating inside one flat region it is just resample dirt, and painting
    it rim-dark scatters holes through the jacket.

    Outline = touches transparency, or has >=2 distinct materials around it.
    """
    pad_bg = np.pad(~opaque, 1, constant_values=True)
    touches_bg = np.zeros(rind.shape, dtype=bool)
    distinct = np.zeros(rind.shape, dtype=np.int16)

    for m in range(len(PALETTE)):
        near = np.zeros(rind.shape, dtype=bool)
        pad_m = np.pad(labels == m, 1)
        for dy in (0, 1, 2):
            for dx in (0, 1, 2):
                if dy == 1 and dx == 1:
                    continue
                near |= pad_m[dy : dy + rind.shape[0], dx : dx + rind.shape[1]]
                if m == 0:
                    touches_bg |= pad_bg[dy : dy + rind.shape[0], dx : dx + rind.shape[1]]
        distinct += near

    return rind & (touches_bg | (distinct >= 2))


def deink(
    idx: np.ndarray,
    opaque: np.ndarray,
    outline: np.ndarray,
    rim_of: np.ndarray,
    n_swatches: int,
    max_passes: int = 8,
) -> np.ndarray:
    """Grow settled regions into the rind, one ring per pass, by 8-neighbour vote.

    Each pass only fills pixels that touch an already-settled pixel, so a thick
    outline dissolves from the outside in and the innermost pixels inherit
    whatever won on the way -- rather than every rind pixel guessing at once.

    Outline pixels take the winning material's rim swatch (a dark tint of that
    material, not black). Everything else copies its neighbour's exact swatch.
    """
    idx = idx.copy()
    for _ in range(max_passes):
        todo = opaque & (idx < 0)
        if not todo.any():
            break
        votes = _neighbour_votes(idx, n_swatches)
        fill = todo & (votes.max(axis=0) > 0)
        if not fill.any():
            break
        won = votes.argmax(axis=0).astype(np.int16)
        idx[fill] = np.where(outline, rim_of[np.clip(won, 0, None)], won)[fill]
    return idx


def despeckle(
    idx: np.ndarray, opaque: np.ndarray, owners: list[str], min_support: int
) -> np.ndarray:
    """Flip pixels that almost no neighbour agrees with, if some other swatch dominates.

    min_support is how many of the 8 neighbours must share a pixel's swatch for it
    to survive; 1 only kills fully isolated pixels, 2 also thins out stray pairs.
    Support is counted per material, not per swatch, so a legitimate highlight
    sitting alone in a field of its own mid-tone is not mistaken for noise.
    """
    if min_support <= 0:
        return idx
    n = len(owners)
    votes = _neighbour_votes(idx, n)

    materials = sorted(set(owners))
    by_material = np.stack(
        [votes[[i for i, o in enumerate(owners) if o == m]].sum(axis=0) for m in materials]
    )
    mat_of = np.array([materials.index(o) for o in owners], dtype=np.int16)
    own_mat = np.where(idx >= 0, mat_of[np.clip(idx, 0, None)], -1)

    support = np.take_along_axis(by_material, np.clip(own_mat, 0, None)[None], axis=0)[0]
    exempt = np.isin(own_mat, [materials.index(m) for m in DESPECKLE_EXEMPT if m in materials])
    lonely = (
        opaque
        & (idx >= 0)
        & ~exempt
        & (support < min_support)
        & (by_material.max(axis=0) > support)
    )

    out = idx.copy()
    out[lonely] = votes.argmax(axis=0)[lonely].astype(np.int16)
    return out


def calibrate(frames_dir: Path) -> str:
    """Re-derive PALETTE and CUTS from the sheets: portrait hue/sat, measured luma.

    Prints a paste-ready block. Re-run after re-exporting art, or after changing
    SHADES / IDENTITY / GAIN.

    Shade boundaries are placed at even population percentiles of each material's
    measured luma, pooled over every calibration sheet. Pooling is what makes
    them global: each individual frame then deviates from that average by however
    much it is actually lit, which is where the shading comes from.
    """
    import colorsys

    acc: dict[str, list[np.ndarray]] = {name: [] for name in PALETTE}
    used = []
    for stem in CALIBRATION_SHEETS:
        path = frames_dir / f"khalid_{stem}_frames.png"
        if not path.exists():
            continue
        used.append(stem)
        a = np.array(Image.open(path).convert("RGBA"))
        rgb = a[..., :3].astype(np.float32) / 255.0
        opaque = a[..., 3] >= ALPHA_CUT
        labels = classify(rgb, opaque)
        lum = luma(rgb)
        for m, name in enumerate(PALETTE):
            mask = opaque & (labels == m)
            if mask.any():
                acc[name].append(lum[mask])

    def at_luma(hue: float, sat: float, target: float) -> str:
        r, g, b = colorsys.hsv_to_rgb(hue / 360.0, sat, 1.0)
        v = min(1.0, max(0.0, target) / (r * 0.299 + g * 0.587 + b * 0.114))
        r, g, b = colorsys.hsv_to_rgb(hue / 360.0, sat, v)
        return f"#{round(r * 255):02X}{round(g * 255):02X}{round(b * 255):02X}"

    def pushed(median: float, value: float) -> float:
        """Move `value` away from `median` by GAIN, multiplicatively."""
        if median <= 0:
            return value
        return median * max(SHADE_FLOOR, (value / median) ** GAIN)

    ramps, cuts = [], []
    for name in PALETTE:
        if not acc[name]:
            continue
        vals = np.concatenate(acc[name])
        med = float(np.median(vals))
        # Shade i sits at the centre of its population band; cuts are the edges.
        centres = [float(np.percentile(vals, (i + 0.5) / SHADES * 100)) for i in range(SHADES)]
        edges = [float(np.percentile(vals, (i + 1) / SHADES * 100)) for i in range(SHADES - 1)]

        ramp = [at_luma(*IDENTITY[name], pushed(med, c)) for c in reversed(centres)]
        ramp.append(at_luma(*IDENTITY[name], pushed(med, centres[0]) * RIM_FACTOR))
        ramps.append(f'    "{name}": ({", ".join(f'"{c}"' for c in ramp)}),  # median {med:.3f}')
        cuts.append(f'    "{name}": ({", ".join(f"{e:.3f}" for e in edges)}),')

    return "\n".join(
        [f"# calibrated from: {', '.join(used)}  (SHADES={SHADES}, GAIN={GAIN})", "PALETTE = {"]
        + ramps
        + ["}", "CUTS = {"]
        + cuts
        + ["}"]
    )


@dataclass
class Stats:
    src_colors: int = 0
    out_colors: int = 0
    opaque: int = 0
    rind: int = 0
    unresolved: int = 0
    per_material: dict[str, int] = field(default_factory=dict)


def repalette(
    path: Path, alpha_cut: int, min_support: int, alpha_mode: str, smooth: int
) -> tuple[Image.Image, Image.Image, Stats]:
    im = Image.open(path).convert("RGBA")
    a = np.array(im)
    rgb = a[..., :3].astype(np.float32) / 255.0

    opaque = a[..., 3] >= alpha_cut

    table, owners = swatch_table()
    st = Stats(opaque=int(opaque.sum()))
    st.src_colors = len(np.unique(a[..., :3][opaque].reshape(-1, 3), axis=0)) if st.opaque else 0

    raw = classify(rgb, opaque)
    st.rind = int((opaque & (raw < 0)).sum())

    # rim_of[s] = the rim swatch belonging to swatch s's material
    stride = SHADES + 1
    rim_of = np.array([(i // stride) * stride + SHADES for i in range(len(table))], dtype=np.int16)
    outline = _is_outline(opaque & (raw < 0), raw, opaque)

    idx = assign_shades(rgb, raw, opaque, smooth)
    idx = deink(idx, opaque, outline, rim_of, len(table))
    idx = despeckle(idx, opaque, owners, min_support)
    st.unresolved = int((opaque & (idx < 0)).sum())

    # Anything still unsettled (an island with no classified neighbour at all)
    # is dropped rather than guessed -- it is a stray resample speck.
    keep = opaque & (idx >= 0)
    out = np.zeros_like(a)
    out[..., :3] = table[np.clip(idx, 0, None)]
    # "harden" is right for the body -- pixel art wants hard edges and the AI's
    # soft halo is just resample residue. But dash/spawn/death draw their ghost
    # trails and flashes *with* alpha, and hardening turns those into solid
    # duplicate bodies, so those sheets need "keep".
    src_alpha = a[..., 3] if alpha_mode == "keep" else np.uint8(255)
    out[..., 3] = np.where(keep, src_alpha, 0)

    for name in PALETTE:
        owned = np.isin(np.clip(idx, 0, None), [i for i, o in enumerate(owners) if o == name])
        st.per_material[name] = int((keep & owned).sum())
    st.out_colors = len(np.unique(out[..., :3][keep].reshape(-1, 3), axis=0)) if keep.any() else 0

    # Debug mask shows the classify pass only (pre-vote), so magenta = what the
    # rules could not claim. That is the view you want when tuning RULES.
    dbg = np.zeros_like(a)
    for name, col in DEBUG_COLORS.items():
        m = (raw < 0) if name is None else (raw == list(PALETTE).index(name))
        dbg[opaque & m] = (*col, 255)

    return Image.fromarray(out), Image.fromarray(dbg), st


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("src", type=Path, help="PNG file, or a directory of PNGs")
    ap.add_argument("-o", "--out", type=Path, help="output dir (default: <src>_repal)")
    ap.add_argument("--alpha-threshold", type=int, default=ALPHA_CUT, help=f"default {ALPHA_CUT}")
    ap.add_argument(
        "--despeckle",
        type=int,
        default=DESPECKLE_SUPPORT,
        metavar="N",
        help=f"flip pixels fewer than N of 8 neighbours agree with; 0 disables "
        f"(default {DESPECKLE_SUPPORT})",
    )
    ap.add_argument(
        "--alpha",
        choices=("harden", "keep"),
        default="harden",
        help="harden: every kept pixel goes fully opaque (default). "
        "keep: preserve source alpha -- needed for dash/spawn/death trails",
    )
    ap.add_argument(
        "--debug", action="store_true", help="also write *_mask.png classification maps"
    )
    ap.add_argument(
        "--smooth",
        type=int,
        default=SMOOTH_RADIUS,
        metavar="R",
        help=f"blur radius for the luma field shade ranking reads; 0 ranks raw "
        f"pixels and mottles flat areas (default {SMOOTH_RADIUS})",
    )
    ap.add_argument(
        "--calibrate",
        action="store_true",
        help="print a PALETTE block re-derived from the sheets, and exit",
    )
    args = ap.parse_args()

    if args.calibrate:
        print(calibrate(args.src if args.src.is_dir() else args.src.parent))
        return

    files = sorted(args.src.glob("*.png")) if args.src.is_dir() else [args.src]
    if not files:
        raise SystemExit(f"no PNGs at {args.src}")

    base = args.src if args.src.is_dir() else args.src.parent
    out_dir = args.out or base.parent / f"{base.name}_repal"
    out_dir.mkdir(parents=True, exist_ok=True)

    for f in files:
        img, dbg, st = repalette(f, args.alpha_threshold, args.despeckle, args.alpha, args.smooth)
        img.save(out_dir / f.name)
        if args.debug:
            dbg.save(out_dir / f"{f.stem}_mask.png")
        mats = " ".join(f"{k}={v}" for k, v in st.per_material.items() if v)
        print(
            f"{f.name:44s} {st.src_colors:5d} -> {st.out_colors:2d} colors | "
            f"{st.opaque:5d}px rind={st.rind:4d} dropped={st.unresolved:3d} | {mats}"
        )
    print(f"\nwrote {len(files)} file(s) to {out_dir}")


if __name__ == "__main__":
    main()
